### ISSUE TITLE
npm install not working on unbuntu ?

### ISSUE THREAD

**Issue by hugolpz** [Ircam-RnD/xmm-soundworks-ours#1]
Hello guys,
I'am teaming up with Mehdi to run your app.

Contexts : 

- Mehdi : Win / Bash shell / Git, Node v6.9.1, npm 3.10.8 ==> fails with `node-gyp` error.
- Hugo : Linux (Bash) shell / Git, Node v6.9.1, npm 3.10.8 ==> Fails (`npm install` runs endlessly without result any)

Hugo's shell after 5mins : 
![screenshot from 2016-10-25 15-42-45](https://cloud.githubusercontent.com/assets/1420189/19688364/b7642a40-9ac9-11e6-845a-c45a5420475b.png)

Note : I (Hugo) successfully install other node apps. Git, node, and npm are working well.

**Comment by josephlarralde** [comment]
Hey hugo,

I don't have time right now to check what's going wrong but 
- the project is broken (whereas it doesn't seem to be related with your issue)
- I'll remove this repo by tomorrow
- I'll replace it by a real template, easier to start with.
So please be patient for one or two days more, then we can start opening issues on the new repo

Best,
J

**Comment by josephlarralde** [comment]
There's a brand new xmm-soundworks-template repository here : 
https://github.com/Ircam-RnD/xmm-soundworks-template

Please consider using this new one as a starting point for the same kind of projects.
I'll delete this repository by tomorrow, as I migrated it on our private forge (it was originally a student's project so it's not supposed to be here)

Best,
J
